### ISSUE TITLE
Clean removes prior builds

### ISSUE THREAD

**Issue by colindean** [ADTRAN/gradle-scala-multiversion-plugin#1]
If I run `gradle clean`, then of course my build directory is cleaned.

If I run `gradle assemble`, then I see the multiple versions output in `build/lib`. 👍 

If I run `gradle clean assemble`, then I see output in `build/lib` for only the last Scala version defined in the `scalaVersions` property.

This leads me to believe without looking at the code that this plugin re-runs every task for each Scala version.

Maybe it should only run `clean` once?

**Comment by kbielefe** [comment]
Thanks for the report, and congrats on finding the first official bug.  We will take a look.
