### ISSUE TITLE
1.0.31 is not released

### ISSUE THREAD

**Issue by koterpillar** [ADTRAN/gradle-scala-multiversion-plugin#11]
The latest version in https://github.com/ADTRAN/gradle-scala-multiversion-plugin/releases is 1.0.31, but it is not published on https://plugins.gradle.org/plugin/com.adtran.scala-multiversion-plugin.

**Comment by nathanalderson** [comment]
CI has been updated and version [1.0.32](https://plugins.gradle.org/plugin/com.adtran.scala-multiversion-plugin/1.0.32) has been published via [build #55](https://travis-ci.org/ADTRAN/gradle-scala-multiversion-plugin/builds/441824290).
