### ISSUE TITLE
Only one jar created when scalaVersions is in ascending order

### ISSUE THREAD

**Issue by wbrege** [ADTRAN/gradle-scala-multiversion-plugin#19]
When I used `scalaVersions = 2.11.8, 2.12.1` it only created the 2.12.1 jar, however it worked as expected when I swapped to `scalaVersions = 2.12.1, 2.11.8`. I wouldn't suggest that this necessarily needs a fix but it should be made explicit in the documentation.

**Comment by nathanalderson** [comment]
The plugin doesn't seem to care which order the versions are in. This worked fine for me:

```
╭ 16:02:12 ~/dev/scratch
╰ » cat build.gradle
buildscript {
  repositories { mavenCentral() }
  dependencies { classpath "com.adtran:scala-multiversion-plugin:1.+" }
}
apply plugin: "scala"
apply plugin: "com.adtran.scala-multiversion-plugin"
task t1() { doLast { println "t1 $project.scalaVersion" } }

╭ 16:02:16 ~/dev/scratch
╰ » cat gradle.properties 
scalaVersions = 2.11.8, 2.12.1

╭ 16:02:20 ~/dev/scratch
╰ » ./gradlew t1

> Task :t1
t1 2.11.8

> Task :scratch:t1
t1 2.12.1

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
```

If you can generate a minimal config that demonstrates the problem, I'll be glad to look into it.

**Comment by nathanalderson** [comment]
Closing for now.
