### ISSUE TITLE
Recursion into other version does not honor 1st version's command line options

### ISSUE THREAD

**Issue by johnsonjsyuen** [ADTRAN/gradle-scala-multiversion-plugin#20]
When recursing into the 2nd version (e.g. when compiling 2.12 and 2.11 in order, 2.11 is the 2nd version), the command line options of the first version are not honored.

We discovered this when we used command line flags to skip tests. E.g. ./gradlew publish -x test
On the first publish task, it will skip testing.
On the 2nd publish task, it will not skip testing.

**Comment by nathanalderson** [comment]
Most flags are passed along, but I was inadvertently overwriting the excluded tasks list rather than extending it. Thanks for catching!
