### ISSUE TITLE
Generated maven pom contains `_%%` in dependencies

### ISSUE THREAD

**Issue by danslapman** [ADTRAN/gradle-scala-multiversion-plugin#25]
even with `maven-publish`

Example:
```scala
...
<dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>%scala-version%</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.typesafe.akka</groupId>
      <artifactId>akka-actor_%%</artifactId>
      <version>2.5.25</version>
      <scope>runtime</scope>
    </dependency>
</dependencies>
```

**Comment by nathanalderson** [comment]
There's actually a [testcase](https://github.com/ADTRAN/gradle-scala-multiversion-plugin/blob/master/src/test/groovy/unit/TestScalaMultiVersionPlugin.groovy#L183-L184) for this. Is there anything else unique about your project?

**Comment by danslapman** [comment]
After some experiments I fugured out that the problem was I used `implementation`/`testImplementation` instead of `compile`/`testCompile`

**Comment by danslapman** [comment]
While `compile`/`testCompile` are deprecated now I think gradle-scala-multiversion-plugin should support `implementation`/`testImplementation` as well

**Comment by koterpillar** [comment]
We've just run into this issue, and we aren't using `implementation` or `testImplementation`. Using Gradle 6.0.1.

**Comment by nathanalderson** [comment]
@danslapman I agree. PR is welcome, or I'll try to get to it sometime.

@koterpillar As mentioned above, there is a testcase for this, so I'd need to understand what is different about your project to cause this not to work.

**Comment by tomnis** [comment]
We ran into this also. We used one of the nebula plugins as a workaround

https://plugins.gradle.org/plugin/nebula.maven-resolved-dependencies

**Comment by nathanalderson** [comment]
If someone can recreate the issue in a unit test or demonstrate it with a minimal `build.gradle` I can try to look into it. Closing for now.
