### ISSUE TITLE
Works incorrectly with multiple modules

### ISSUE THREAD

**Issue by asm0dey** [ADTRAN/gradle-scala-multiversion-plugin#34]
I have a multimodule project, where different modules should be built against different sets of java versions.
Say module `a` should be built against 2.11.2 and 2.12.4, while module `b` should be built only against 2.12

Currently build has weird recursion where `a` recurses into building `b` with its own `scalaVersions` and obviously second one fails because of invalid dependency.

**Comment by nathanalderson** [comment]
As noted in the README, building subprojects for different versions of Scala is not supported. This is a known limitation and something that I don't expect to fix.
